---
title: "KS Data"
author: "Josh"
output: html_document
---


```{r echo=FALSE}

library(dplyr)
library(dtplyr)
library(collapse)
library(tidyr)
library(data.table)
library(splines)
library(survey)
library(mitools)
library(mvtnorm)
library(kableExtra)

```



```{r}
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cohort_imp1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4_1.Rda") 
#all_cd4_1 = all_cd4_1 |> filter(!is.na(month_avg_cd4))
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4.Rda") 
patients_all = fread("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Sampling_frame/patients_all.csv")
names(patients_all)="patient"



load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long.Rda") 



all_val_long4$R=1

d_1 = all_cohort_imp1 |> filter(patient %in% all_val_long$patient)  |> left_join(all_val_long4[,c('patient','R')]) |> count(patient,stop_d,program,death_y,R) |> mutate(n=NULL,R=if_else(is.na(R),0,R))

```


```{r}
#### Single imputation for filling in missing cd4 values in phase 1 and phase 2

#### use one row for all patients in cohort 
d = all_cohort_imp1 |> inner_join(patients_all,by="patient")  
  
## Remove patients w/ dis_d < as.Date("2009-12-01")
d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  

  #### expanded monthly data
  
  #add rows for each month
  setDT(d1)
  # floor start and end month
  ## start_d is the earlier of enrol_d and earliest cd4_d
  ## stop_d is the latest of l_alive_d,last_visit_d,death_d
  d1[, start_month := lubridate::floor_date(start_d, unit = "month")]
  d1[, end_month := lubridate::floor_date(stop_d, unit = "month")]

    d2<-d1[, .(year_month = format(seq(start_month, end_month, by = "1 month"), "%Y-%m")), by = .(patient,birth_d,birth_d_final,enrol_d,enrol_d_final,male, male_final,dis_d, canc_d_final,art_sd, recart_d_final, death_y,death_y_final,death_d,death_d_final,l_alive_d_final, start_d,start_d_final, stop_d, program,V)]
    
    ### merge cd4 values in by year_month from phase 1 and phase 2 long datasets and create variables below, carry forward cd4 12 months and then cutoff at 2010 forward
  
## Add unvalidated CD4 and validated CD4 
d3 = d2 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by=c("patient","year_month")) |> left_join(all_val_long4[,c("patient","year_month","month_avg_cd4_final")],by=c("patient","year_month")) 


  d3=d3 %>% lazy_dt() |> group_by(patient) %>% mutate(new_v = if_else(is.na(month_avg_cd4),NA,row_number())) |> fill(new_v) |> mutate(row_diff = row_number()-new_v,cd4_1=month_avg_cd4) |> fill(cd4_1,.direction = "down") |> mutate(cd4_2=cd4_1) |> fill(cd4_1,.direction = "up") |>fill(new_v,.direction = "up") |> mutate(cd4=if_else(row_number() < 7 & new_v <=7, cd4_1, cd4_2)) |> ungroup() |> as.data.frame()
  
 d4=d3 %>% lazy_dt() |> group_by(patient) %>% mutate(new_v = if_else(is.na(month_avg_cd4_final),NA,row_number())) |> fill(new_v) |> mutate(row_diff = row_number()-new_v,cd4_1=month_avg_cd4_final) |> fill(cd4_1,.direction = "down") |> mutate(cd4_2=cd4_1) |> fill(cd4_1,.direction = "up") |>fill(new_v,.direction = "up") |> mutate(cd4_final=if_else(row_number() < 7 & new_v <=7, cd4_1, cd4_2))  |> ungroup() |> as.data.frame()
  
## eligibility criteria of removing prevalent cases and KS cases >60 days before enrollment; adding ks indicator for imputation
 
# d5 = d4 |> mutate(prevalent = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60 & dis_d >= enrol_d - 60,1,0)) |> mutate(prevalent_final = if_else(V==0,0, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60 & canc_d_final >= enrol_d_final - 60,1,0))) |> filter(prevalent == 0 &  prevalent_final==0 & (is.na(canc_d_final) | as.Date(canc_d_final)>=as.Date("2009-12-01"))) 

d5 = d4 |> mutate(prevalent_remove = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60,1,0)) |> mutate(prevalent_remove_final = if_else(V==0,0, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60,1,0))) |> filter(prevalent_remove == 0 &  prevalent_remove_final==0 & (is.na(canc_d_final) | as.Date(canc_d_final)>=as.Date("2009-12-01"))) 

## Age each month
d5$age<-as.numeric(round((as.Date(paste(d5$year_month, "-01", sep=""))-d5$birth_d)/365.25,1))
d5$age_final<-as.numeric(round((as.Date(paste(d5$year_month, "-01", sep=""))-d5$birth_d_final)/365.25,1))

## ART has started indicator
d5$art_ind<-ifelse(is.na(d5$art_sd) | d5$art_sd > as.Date(paste(d5$year_month, "-01", sep="")),0,1)
d5$art_ind_final<-ifelse(is.na(d5$recart_d_final) | d5$recart_d_final > as.Date(paste(d5$year_month, "-01", sep="")),0,1)

## Add year to each row
d5$year<-as.numeric(substr(d5$year_month,1,4)) 

d5 = d5 |> lazy_dt() |> mutate(ks_year_month = format(dis_d, "%Y-%m"), ks_year_month_final = format(canc_d_final, "%Y-%m"))  |> mutate(ks_ind = if_else(!is.na(dis_d) & ks_year_month == year_month,1,0), ks_ind_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final) & ks_year_month_final == year_month & as.Date(canc_d_final) >= as.Date("2009-12-01"),1,0))) |> filter(program == 1 & year_month >= "2009-12" | program == 0 & year_month >= "2010-01" )  |> ungroup() |> as.data.frame()

d5 = d5 |> lazy_dt() |>  group_by(patient) |> mutate(cd4_rt=sqrt(cd4),cd4_rt_final=sqrt(cd4_final),row=row_number()) |> ungroup() |> as.data.frame()

# 
# d6 = d5 |> lazy_dt() |> mutate(ks=if_else(!is.na(dis_d),1,0),ks_final=if_else(!is.na(canc_d_final),1,0), start_d1=if_else(as.Date(start_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(start_d)),stop_d1=if_else(as.Date(stop_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(stop_d)),dis_d1=if_else(as.Date(dis_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(dis_d)),start_d_final1=if_else(as.Date(start_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(start_d_final)), canc_d_final1=if_else(as.Date(canc_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(canc_d_final)),time=if_else(is.na(dis_d),as.numeric(as.Date(stop_d)-as.Date(start_d1))+1,as.numeric(as.Date(dis_d1)-as.Date(start_d1))+1),time_final=if_else(is.na(canc_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(start_d_final1))+1,as.numeric(as.Date(canc_d_final1)-as.Date(start_d_final1))+1)) |> ungroup() |> as.data.frame()

d6 = d5 |> lazy_dt() |> mutate(ks=if_else(!is.na(dis_d),1,0),ks_final=if_else(!is.na(canc_d_final),1,0), enrol_d1=if_else(as.Date(enrol_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(enrol_d)),stop_d1=if_else(as.Date(stop_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(stop_d)),dis_d1=if_else(as.Date(dis_d)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(dis_d)),enrol_d_final1=if_else(as.Date(enrol_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(enrol_d_final)), canc_d_final1=if_else(as.Date(canc_d_final)< as.Date("2010-01-01"),as.Date("2010-01-01"),as.Date(canc_d_final)),time=if_else(is.na(dis_d),as.numeric(as.Date(stop_d)-as.Date(enrol_d1))+1,as.numeric(as.Date(dis_d1)-as.Date(enrol_d1))+1),time_final=if_else(is.na(canc_d_final),as.numeric(as.Date(l_alive_d_final)-as.Date(enrol_d_final1))+1,as.numeric(as.Date(canc_d_final1)-as.Date(enrol_d_final1))+1),enrol_d_year_month=format(enrol_d, "%Y-%m")) |> ungroup() |> as.data.frame()


### remove months prior to the month of enrollment
d6 = d6 |> filter(year_month>=enrol_d_year_month & year_month>="2010-01") 



### cd4 missingness


# ch= d6 |>  group_by(patient) |> filter(V==1 & row_number()==1)
# 
# ch1=ch[is.na(ch$cd4_rt_final),]
# 
# ch2=length(unique(d6[!is.na(d6$cd4_rt_final) & d6$V==1,]$patient))

### 255150 total and 203880 have at least one

### 830 total and 96 have at least one

```



```{r}
# MI error prone w/o MI eligibility
m=10
j=0
set.seed(1993)
betas_ipw_inc1 = vcovs_ipw_inc1 = betas_gr_mi_inc1 = vcovs_gr_mi_inc1 = betas_ipw_inc2 = vcovs_ipw_inc2 = betas_gr_mi_inc2 = vcovs_gr_mi_inc2 = betas_ipw_inc3 = vcovs_ipw_inc3 = betas_gr_mi_inc3 = vcovs_gr_mi_inc3 = betas_ehr_inc = vcovs_ehr_inc = vector("list", m)

for(i in 1:m){
  
    ### imputation for phase 1 cd4 values based on error prone variables
    mod5 = lm(cd4_rt ~  male +program+ ns(age,df=4) + year +art_ind +  ks*ns(time,df=4), data= d6[d6$row==1,]) 
   ## to easily get design matrix for the full cohort
    d6_1 = d6 |> mutate(cd4_rt=1)
    v3=model.matrix(terms(mod5),d6_1)
    beta2 = mod5$coefficients
    vcov2 = vcov(mod5)
    rmvs2=rmvnorm(n=1,beta2,vcov2)
    rmvs2 = as.vector(rmvs2)
    cd4_rt_new = as.vector((v3 %*% rmvs2) + sample(resid(mod5),1))
    d6$cd4_rt_init_imp=if_else(d6$row==1 & is.na(d6$cd4_rt),cd4_rt_new,d6$cd4_rt)
    ### any imputed CD4<0 assign a 1
    d6$cd4_rt_init_imp=if_else(d6$cd4_rt_init_imp<0,1,d6$cd4_rt_init_imp)
    
    d6 = d6 |> fill(cd4_rt_init_imp)

  ### imputation for phase 2 cd4 values
  mod6 = lm(cd4_rt_final ~  male_final +program+ ns(age_final,df=4) + ns(cd4_rt_init_imp,df=4) + year +art_ind_final + ks_final*ns(time_final,df=4), data= d6[d6$row==1 & d6$V==1,])
    ## to easily get design matrix for phase 2
  d5_2=d6[d6$V==1,]
  d6_1 = d5_2 |> mutate(cd4_rt_final=1)
   v4=model.matrix(terms(mod6),d6_1)
  beta2 = mod6$coefficients
  vcov2 = vcov(mod6)
  rmvs2=rmvnorm(n=1,beta2,vcov2)
  rmvs2 = as.vector(rmvs2)
  cd4_rt_final_new = as.vector((v4 %*% rmvs2) + sample(resid(mod6),1))
  d5_2$cd4_rt_imp_final=if_else(d5_2$row==1 & d5_2$V==1 & is.na(d5_2$cd4_rt_final),cd4_rt_final_new,d5_2$cd4_rt_final)
  d5_2$cd4_rt_imp_final=if_else(d5_2$cd4_rt_imp_final<0,1,d5_2$cd4_rt_imp_final)
    d5_2 = d5_2 |> fill(cd4_rt_imp_final)
    d6$cd4_rt_imp_final = NA
    d6 = rbind(d6[d6$V==0,],d5_2) 
    

d6_val = d6[d6$V==1,] |> mutate(enrol_d_final_year_month=format(enrol_d_final1, "%Y-%m")) |> filter(enrol_d_final_year_month <= year_month)
  
suppressWarnings({d_inc_val=   d6_val |> lazy_dt() |> group_by(patient) |> mutate(ct=rleid(cd4_rt_imp_final)) |>  filter(row_number() <= min(which(ks_ind_final == 1)))  |> ungroup() |> group_by(patient,year,art_ind_final,cd4_rt_imp_final,ct,birth_d_final,enrol_d_final1) |> summarize(ks_ind_final=max(ks_ind_final),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25 ,pys_final=n/12) |> ungroup() |> as.data.frame()})

# suppressWarnings({d_inc_val=   d6[d6$V==1,] |> lazy_dt() |> group_by(patient) |> mutate(ct=rleid(cd4_rt_imp_final)) |>  filter(row_number() <= min(which(ks_ind_final == 1)))  |> ungroup() |> group_by(patient,year,art_ind_final,cd4_rt_imp_final,ct,birth_d_final,enrol_d_final) |> summarize(ks_ind_final=max(ks_ind_final),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25 ,pys_final=n/12) |> ungroup() |> as.data.frame()})
    
d_inc_val2 = d_inc_val |> lazy_dt() |> left_join(unique(d6[d6$V==1,c("patient","V","program","male_final")])) |> mutate(V1=V) |> ungroup() |> as.data.frame()

suppressWarnings({d_inc =   d6 |> lazy_dt() |> group_by(patient)|> mutate(ct=rleid(cd4_rt_init_imp)) |>  filter(row_number() <= min(which(ks_ind == 1)))  |> ungroup() |> group_by(patient,year,art_ind,cd4_rt_init_imp,ct,birth_d,enrol_d) |> summarize(ks_ind=max(ks_ind),n=max(row_number()),min_date=min(year_month),max_date=max(year_month))|> mutate(age = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d)/365.25 ,pys=n/12) |> ungroup() |> as.data.frame()})

d_inc2 = d_inc  |> lazy_dt() |> left_join(unique(d6[,c("patient","V","program","male")])) |> ungroup() |> as.data.frame()
d_inc2$year1 = ifelse(d_inc2$year==2009,2010,d_inc2$year)

mod_ehr_inc = glm(ks_ind ~ male+program+I(age/10)+I(year1-2010)+art_ind + cd4_rt_init_imp,offset = log(pys/1000),data= d_inc2, family = poisson)


### intersection between phase 1 and phase 2
d_inc_val3 = d_inc2 |> left_join(d_inc_val2[,c("patient","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final")]) 
d_inc_val3$year1 = ifelse(d_inc_val3$year==2009,2010,d_inc_val3$year)


### Get overlapping timeframes
## get date ranges for each patient who was validated based on their phase 1 and phase 2 data
### phase 1
cc1=d_inc2[d_inc2$V==1,] |> lazy_dt() |> group_by(patient) |> summarize(n1=max(row_number()),d_min1=min(min_date),d_max1=max(max_date)) |> ungroup() |> as.data.frame()
### phase 2
cc2=d_inc_val2[d_inc_val2$V==1,] |> lazy_dt() |> group_by(patient) |> summarize(n2=max(row_number()),d_min2=min(min_date),d_max2=max(max_date)) |> ungroup() |> as.data.frame()

### phase-1 and phase-2 date ranges and rows for V==1
cc3=cc1 |> left_join(cc2) |> mutate(min_date1= pmax(d_min1,d_min2),max_date1= pmin(d_max1,d_max2))

#### same number of rows and same date range
patients1_1 = cc3 |> filter(n1==n2 & d_min1==d_min2 & d_max1==d_max2)

#### different number of rows or different date range
patients1_2 = cc3 |> filter(n1!=n2 | d_min1!=d_min2 | d_max1!=d_max2)

#######################################################################################################################################
#######################################################################################################################################
## deal with 109 patients with differing number of rows or different date range between phase 1 and phase 2
### phase 1
d_inc2_v0 = d_inc2[d_inc2$V==1,] |> inner_join(patients1_2[,c('patient','min_date1','max_date1')]) |> filter(min_date>=min_date1 & max_date<=max_date1)
### phase 2
d_inc_val2_v0 = d_inc_val2[d_inc_val2$V==1,] |> inner_join(patients1_2[,c('patient','min_date1','max_date1')])  |> filter(min_date>=min_date1 & max_date<=max_date1)

d_all1 = d_inc2_v0 |> full_join(d_inc_val2_v0[,c("patient","birth_d_final","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final","V1")]) 
d_all1$year1 = ifelse(d_all1$year==2009,2010,d_all1$year)

d_all2 = d_all1 |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date)

### updated rows for 109 patients
d_all3_2 = d_all2 |> group_by(patient) |> filter(min_date!=lag(min_date) | max_date!=lead(max_date) | row_number()==1)  |> filter(min_date!=lag(min_date) | max_date!=lead(min_date) | row_number()==1) |> mutate(max_date1=if_else(min_date>lag(max_date) & max_date==lead(max_date) & min_date<lead(max_date),min_date,max_date),max_date1=if_else(is.na(max_date1),max_date,max_date1)) |> mutate(max_date2=if_else(min_date<lag(max_date1) & max_date1==lead(max_date1),lag(max_date1),max_date1),max_date2=if_else(is.na(max_date2),max_date1,max_date2)) |> filter(min_date != lag(min_date) | row_number()==1) |> mutate(max_date=max_date2,max_date1=NULL,max_date2=NULL)

## deal with patients with same number of rows and date ranges between phase 1 and phase 2

### phase 1
d_inc2_v1 = d_inc2[d_inc2$V==1,] |> inner_join(patients1_1[,c('patient','min_date1','max_date1')]) |> filter(min_date>=min_date1 & max_date<=max_date1)
### phase 2
d_inc_val2_v1 = d_inc_val2 |> inner_join(patients1_1[,c('patient','min_date1','max_date1')])  |> filter(min_date>=min_date1 & max_date<=max_date1)

## limit patients with same number of rows and overall date ranges to those with different dates on individual rows
### 702/722 have the exact same dates on each row, 20 do not have the same dates on each row

d_all5 = d_inc2_v1 |> full_join(d_inc_val2_v1[,c("patient","birth_d_final","min_date","max_date","male_final","pys_final","ks_ind_final","art_ind_final","age_final","cd4_rt_imp_final","V1")]) |> group_by(patient) |> filter(any(is.na(V) | is.na(V1)))

d_all6 = d_all5 |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date) 

### updated rows for 20 patients who do not have the same dates on each row
d_all7 = d_all6 |> group_by(patient) |> filter(min_date!=lag(min_date) | max_date!=lead(max_date) | row_number()==1) |> mutate(max_date1=if_else(max_date==lead(max_date) & min_date<lag(max_date),lag(max_date),max_date),max_date1=if_else(is.na(max_date1),max_date,max_date1)) |> filter(min_date!=lag(min_date) | max_date1!=lead(max_date1)) |> mutate(max_date1=if_else(min_date==lag(max_date1) & max_date1==lead(max_date1),lag(max_date1),max_date1)) |> filter(min_date!=lag(min_date) | max_date1!=lead(max_date1) | row_number()==1)|>
mutate(min_date1=if_else(min_date==lag(min_date) & max_date1==lead(min_date),max_date1,min_date)) |> filter(min_date1!=lag(min_date1) | min_date1!=lag(max_date1) | row_number()==1)|> mutate(max_date2=if_else(max_date1==lead(max_date1),min_date1,max_date1),max_date2=if_else(is.na(max_date2),max_date1,max_date2)) |> mutate(min_date=min_date1,max_date=max_date2,min_date1=NULL,max_date1=NULL,max_date2=NULL)



d_c = d_inc2_v1 |> filter(!(patient %in% d_all5$patient))

### rows that match for 728 patients
d_c1 = d_c |> select(patient,min_date,max_date) |> arrange(patient,min_date,max_date)

### all rows for validated patients
prows= rbind(d_all3_2,d_all7,d_c1) |> arrange(patient,min_date)


prows1 = prows |> left_join(d_inc_val2,join_by(patient, min_date>=min_date,   min_date<=max_date, max_date<=max_date, max_date>=min_date)) |> mutate(min_date=min_date.x,max_date=max_date.x,min_date.x=NULL,max_date.x=NULL,min_date.y=NULL,max_date.y=NULL)

prows2 = prows1 |> left_join(d_inc2[d_inc2$V==1,],join_by(patient, min_date>=min_date,   min_date<=max_date, max_date<=max_date, max_date>=min_date)) |> mutate(min_date=min_date.x,max_date=max_date.x,min_date.x=NULL,max_date.x=NULL,min_date.y=NULL,max_date.y=NULL,ct.x=NULL,ct.y=NULL,n.x=NULL,n.y=NULL,year=year.x,V=V.x,program=program.x) |> mutate(year.x=NULL,year.y=NULL,V.x=NULL,V.y=NULL,pys=NULL,pys_final=NULL,age=NULL,program.x=NULL,program.y=NULL) |> mutate(n=as.numeric(substr(max_date,6,7))-as.numeric(substr(min_date,6,7))+1) |> mutate(age = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d)/365.25,age_final = as.numeric(as.Date(paste(max_date, "-01", sep="")) - birth_d_final)/365.25,pys=n/12,pys_final=n/12)


d_inc2_c = d_inc2 |> filter(!(patient %in% unique(prows2$patient)))

p_all= rbind(prows2,d_inc2_c)


d_2 = d_1 |> filter(patient %in% unique(p_all$patient))
mod_w = glm(R ~ stop_d + program + death_y, family=binomial,data = d_2)
mod_p<- mod_w$fitted.values
d_p = data.frame(d_2,p_est=mod_p)

load(file="~/Desktop/PhD/Research/KS_Data/Code/wgts_by_hand.Rda")

#################################################################################################################
#### estimated weights including nonresponse probabilities from the incidence analysis cohort
#load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/d_p.Rda") 
pb1=p_all |> left_join(d3,by="patient") |> count(patient,strata,V) |> left_join(d_p[,c('patient','p_est')],by="patient")
mod_w = glm(V ~ strata, family=binomial,data = pb1)
mod_p <- mod_w$fitted.values
pb2 = data.frame(pb1,p_est_overall=mod_p)
pb2 = pb2 |> mutate(w_est = 1/(p_est_overall*p_est))
d_inc_cw = p_all |> left_join(pb2[,c('patient','w_est')],by="patient")

#################################################################################################################

############################################################################################################    
############################################################################################################

## IPW with all rows per patient
d_inc_c= merge(x=d_inc_val2,y=d3,all.x=TRUE,by="patient")
d_inc_cc = d_inc_c |> left_join(pb2[,c('patient','w_est')],by="patient")
d_inc_cc$year1 = ifelse(d_inc_cc$year==2009,2010,d_inc_cc$year)

designMF_4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d_inc_cc,subset=~V==1,method="approx")
ipw_inc_all = svyglm(ks_ind_final ~ male_final + program + I(age_final/10) + I(year1-2010) + art_ind_final + cd4_rt_imp_final, offset = log(pys_final/1000), design=designMF_4, family = poisson)

#################################################################################################################

d_inc_cw$year1= ifelse(d_inc_cw$year==2009,2010,d_inc_cw$year)

mod_ehr_inc2 = glm(ks_ind ~ male+program+I(age/10)+I(year1-2010)+art_ind + cd4_rt_init_imp,offset = log(pys/1000),data= d_inc_cw, family = poisson) 

  #### Raking
  IF_func <- function(fit){
    MM <- model.matrix(fit)
    Score.P   <- fit$y*MM - MM*exp(fit$linear.predictors)
    InfoMat.P <- t(MM*sqrt(exp(fit$linear.predictors))) %*% (MM*sqrt(exp(fit$linear.predictors)))/nrow(MM)
    inffunc <- (Score.P) %*% solve(InfoMat.P)
    inffunc
  }    
naiveInfl3 =  IF_func(mod_ehr_inc2)[,-1]
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_inc_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc_2 = svyglm(ks_ind_final ~ male_final + program + I(age_final/10) + I(year1-2010) + art_ind_final + cd4_rt_imp_final, offset = log(pys_final/1000), design=Ninflcal3, family = poisson)

ipw_inc_3 = svyglm(ks_ind_final ~ male_final + program + I(age_final/10) + I(year1-2010) + art_ind_final + cd4_rt_imp_final, offset = log(pys_final/1000), design=designMF4, family = poisson)


##################################################
# 
#  betas_ipw_inc1[[i]] = coef(ipw_inc_c1)
#  vcovs_ipw_inc1[[i]]  = vcov(ipw_inc_c1)
#  betas_gr_mi_inc1[[i]]  = coef(fit_gr_inc1)
#  vcovs_gr_mi_inc1[[i]]  = vcov(fit_gr_inc1)
# 
# betas_ipw_inc2[[i]] = coef(ipw_inc_2)
# vcovs_ipw_inc2[[i]]  = vcov(ipw_inc_2)
# betas_gr_mi_inc2[[i]]  = coef(fit_gr_inc_1)
# vcovs_gr_mi_inc2[[i]]  = vcov(fit_gr_inc_1)

betas_ipw_inc3[[i]] = coef(ipw_inc_3)
vcovs_ipw_inc3[[i]]  = vcov(ipw_inc_3)
betas_gr_mi_inc3[[i]]  = coef(fit_gr_inc_2)
vcovs_gr_mi_inc3[[i]]  = vcov(fit_gr_inc_2)

betas_ipw_inc2[[i]] = coef(ipw_inc_all)
vcovs_ipw_inc2[[i]]  = vcov(ipw_inc_all)

betas_ehr_inc[[i]] = coef(mod_ehr_inc)
vcovs_ehr_inc[[i]] = vcov(mod_ehr_inc)

j=j+1
print(j)

}

 #wgt_inc_results1=MIcombine(betas_ipw_inc1,vcovs_ipw_inc1)
 #rak_inc_results1=MIcombine(betas_gr_mi_inc1,vcovs_gr_mi_inc1)

#wgt_inc_results2=MIcombine(betas_ipw_inc2,vcovs_ipw_inc2)
#rak_inc_results2=MIcombine(betas_gr_mi_inc2,vcovs_gr_mi_inc2)

wgt_inc_results3=MIcombine(betas_ipw_inc3,vcovs_ipw_inc3)
rak_inc_results3=MIcombine(betas_gr_mi_inc3,vcovs_gr_mi_inc3)

wgt_inc_results2=MIcombine(betas_ipw_inc2,vcovs_ipw_inc2)

ehr_inc_results=MIcombine(betas_ehr_inc,vcovs_ehr_inc)



```


```{r}
# Multiple imputation for measurement error correction
m=10
betas_mi_inc = vcovs_mi_inc = vector("list", m)

for(i in 1:m){
  
#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/ks_mi_",i,".csv")) 
#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/overall_no_ks/ks_mi_",i,".csv")) 


d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/overall_ppv_npv/ks_mi_",i,".csv")) 

#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/by_site/ks_mi_",i,".csv")) 

#d11 = d10 |> select(patient,program,year_month,art_ind_imp,male_imp,enrol_d_imp_year_month,cd4_rt_imp,birth_d_imp,ks_ind_imp)

d11 = d10 |> select(patient,program,year_month,art_ind_imp,male_imp,enrol_d1_year_month,cd4_rt_imp,birth_d_imp,ks_ind_imp)


d11$year<-as.numeric(substr(d11$year_month,1,4)) 

d11$cd4_rt_imp1= round(d11$cd4_rt_imp)
 
### follow up starts at enrollment
suppressWarnings({d_inc_a =   d11 |> lazy_dt() |> group_by(patient)  |> filter(year_month>=enrol_d1_year_month & year_month>="2010-01") |> mutate(ct=rleid(cd4_rt_imp1),date=as.Date(paste(year_month, "-01", sep="")),enrol_d1_year_month_date=as.Date(paste(enrol_d1_year_month, "-01", sep=""))) |> arrange(patient,year_month) |>  filter(row_number() <= min(which(ks_ind_imp == 1))) |> ungroup() |> as.data.frame()})

d_inc_a1 = d_inc_a |> lazy_dt() |> mutate(prevalent = if_else(ks_ind_imp==1 & date <= enrol_d1_year_month_date + 60,1,0))|> group_by(patient) |> filter(all(prevalent == 0)) |> ungroup() |> as.data.frame()

# suppressWarnings({d_inc_a =   d11 |> lazy_dt() |> group_by(patient)  |> filter(year_month>=enrol_d1_year_month & year_month>="2010-01") |> mutate(ct=rleid(cd4_rt_imp1),date=as.Date(paste(year_month, "-01", sep="")),enrol_d1_year_month_date=as.Date(paste(enrol_d1_year_month, "-01", sep=""))) |> arrange(patient,year_month) |>  filter(row_number() <= min(which(ks_ind == 1))) |> ungroup() |> as.data.frame()})
# 
# d_inc_a1 = d_inc_a |> lazy_dt() |> mutate(prevalent = if_else(ks_ind==1 & date <= enrol_d1_year_month_date + 60,1,0))|> group_by(patient) |> filter(all(prevalent == 0)) |> ungroup() |> as.data.frame()

d_inc_a2=d_inc_a1 |> fgroup_by(patient,program,year,art_ind_imp,male_imp,cd4_rt_imp1,ct,birth_d_imp)|> fsummarise(ks_ind_imp=max(ks_ind_imp),min_date=min(year_month),max_date=max(year_month)) |>  roworder(patient,min_date)  |> fungroup()

d_inc_a2$age_imp<-as.numeric(as.Date(paste(d_inc_a2$max_date, "-01", sep="")) - as.Date(d_inc_a2$birth_d_imp))/365.25 
d_inc_a2$n = as.numeric(substr(d_inc_a2$max_date,6,7))-as.numeric(substr(d_inc_a2$min_date,6,7)) + 1
d_inc_a2$pys=d_inc_a2$n/12
d_inc_a2$year<-as.numeric(substr(d_inc_a2$min_date,1,4)) 
      
## MI

fit_mi_inc = glm(ks_ind_imp ~ male_imp + program + I(age_imp/10) + I(year-2010) + art_ind_imp + cd4_rt_imp1, offset = log(pys/1000), family = poisson, data = d_inc_a2)

betas_mi_inc[[i]] = coef(fit_mi_inc)
vcovs_mi_inc[[i]] = vcov(fit_mi_inc)
}


#mi_inc_results1=MIcombine(betas_mi_inc,vcovs_mi_inc)

mi_inc_results2=MIcombine(betas_mi_inc,vcovs_mi_inc)

mi_inc_results=MIcombine(betas_mi_inc,vcovs_mi_inc)

save(wgt_inc_results3,rak_inc_results3,ehr_inc_results,mi_inc_results1,mi_inc_results2,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_error_prone2_nr_elig.Rda") 

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_error_prone2_nr_elig.Rda") 

################################################################################################


lst= list(wgt_inc_results3,rak_inc_results3,ehr_inc_results,mi_inc_results2,mi_inc_results1)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients[-1]
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0))[-1])), betas + 1.96*(sqrt(diag(vcov(res0))[-1])))
  res2[[j]] <- exp(cis3)
}


ktab9 = cbind(IRR = format(round(res2[[1]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),
              IRR = format(round(res2[[2]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),
              IRR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)),IRR = format(round(res2[[4]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[4]][,2],2),nsmall=2)," - ",format(round(res2[[4]][,3],2),nsmall=2)),IRR = format(round(res2[[5]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[5]][,2],2),nsmall=2)," - ",format(round(res2[[5]][,3],2),nsmall=2)))


rownames(ktab9)=c('Male sex','East Africa','Age x 10 years','Year','ART','Sq. rt. CD4')
ktab9 <- kable(ktab9,booktabs=T)

kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","IPW" = 2,"GR" = 2,"EHR" = 2,"MI KS Overall" = 2,"MI KS by Site" = 2))
```



```{r}

tab_inc1 = data.frame(labeltext=c("Male sex","Male sex","Male sex","Male sex","Male sex","East Africa","East Africa","East Africa","East Africa","East Africa","Age x 10 years","Age x 10 years","Age x 10 years","Age x 10 years","Age x 10 years","Year","Year","Year","Year","Year","ART","ART","ART","ART","ART","CD4 (sq. root)","CD4 (sq. root)","CD4 (sq. root)","CD4 (sq. root)","CD4 (sq. root)"),mean=c(res2[[1]][1],res2[[2]][1],res2[[3]][1],res2[[4]][1],res2[[5]][1],res2[[1]][2],res2[[2]][2],res2[[3]][2],res2[[4]][2],res2[[5]][2],res2[[1]][3],res2[[2]][3],res2[[3]][3],res2[[4]][3],res2[[5]][3],res2[[1]][4],res2[[2]][4],res2[[3]][4],res2[[4]][4],res2[[5]][4],res2[[1]][5],res2[[2]][5],res2[[3]][5],res2[[4]][5],res2[[5]][5],res2[[1]][6],res2[[2]][6],res2[[3]][6],res2[[4]][6],res2[[5]][6]), lower=c(res2[[1]][7],res2[[2]][7],res2[[3]][7],res2[[4]][7],res2[[5]][7],res2[[1]][8],res2[[2]][8],res2[[3]][8],res2[[4]][8],res2[[5]][8],res2[[1]][9],res2[[2]][9],res2[[3]][9],res2[[4]][9],res2[[5]][9],res2[[1]][10],res2[[2]][10],res2[[3]][10],res2[[4]][10],res2[[5]][10],res2[[1]][11],res2[[2]][11],res2[[3]][11],res2[[4]][11],res2[[5]][11],res2[[1]][12],res2[[2]][12],res2[[3]][12],res2[[4]][12],res2[[5]][12]),upper=c(res2[[1]][13],res2[[2]][13],res2[[3]][13],res2[[4]][13],res2[[5]][13],res2[[1]][14],res2[[2]][14],res2[[3]][14],res2[[4]][14],res2[[5]][14],res2[[1]][15],res2[[2]][15],res2[[3]][15],res2[[4]][15],res2[[5]][15],res2[[1]][16],res2[[2]][16],res2[[3]][16],res2[[4]][16],res2[[5]][16],res2[[1]][17],res2[[2]][17],res2[[3]][17],res2[[4]][17],res2[[5]][17],res2[[1]][18],res2[[2]][18],res2[[3]][18],res2[[4]][18],res2[[5]][18]),group=c("IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site"))



fpDraw3CI = function (lower_limit, estimate, upper_limit, size, y.offset = 0.5, 
    clr.line, clr.marker, lwd, lty = 1, vertices, vertices.height = 0.1, 
    pch = 8, shapes_gp = fpShapesGp(), shape_coordinates = structure(c(1, 
        1), max.coords = c(1, 1)), ...) 
{
    if (is.na(lower_limit) || is.na(estimate) || is.na(upper_limit)) {
        return()
    }
    forestplot:::prFpDrawLine(lower_limit = lower_limit, upper_limit = upper_limit, 
        line_gp = prGetShapeGp(shapes_gp, shape_coordinates, 
            "lines", default = forestplot:::prDefaultGp(col = clr.line, lwd = lwd, 
                lty = lty)), vertices_gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "vertices", nodefault = TRUE), 
        y.offset = y.offset, vertices = vertices, vertices.height = vertices.height)
    box <- convertX(unit(estimate, "native"), "npc", valueOnly = TRUE)
    if (box >= 0 && box <= 1) {
        if (!is.unit(size)) {
            size <- unit(size, "snpc")
        }
        grid.points(x = unit(estimate, "native"), y = unit(y.offset, 
            "npc"), size = size, pch = pch, gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "box", default = gpar(fill = clr.marker, 
                col = clr.marker)))
    }
}


fpDraw4CI = function (lower_limit, estimate, upper_limit, size, y.offset = 0.5, 
    clr.line, clr.marker, lwd, lty = 1, vertices, vertices.height = 0.1, 
    pch = 24, shapes_gp = fpShapesGp(), shape_coordinates = structure(c(1, 
        1), max.coords = c(1, 1)), ...) 
{
    if (is.na(lower_limit) || is.na(estimate) || is.na(upper_limit)) {
        return()
    }
    forestplot:::prFpDrawLine(lower_limit = lower_limit, upper_limit = upper_limit, 
        line_gp = prGetShapeGp(shapes_gp, shape_coordinates, 
            "lines", default = forestplot:::prDefaultGp(col = clr.line, lwd = lwd, 
                lty = lty)), vertices_gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "vertices", nodefault = TRUE), 
        y.offset = y.offset, vertices = vertices, vertices.height = vertices.height)
    box <- convertX(unit(estimate, "native"), "npc", valueOnly = TRUE)
    if (box >= 0 && box <= 1) {
        if (!is.unit(size)) {
            size <- unit(size, "snpc")
        }
        grid.points(x = unit(estimate, "native"), y = unit(y.offset, 
            "npc"), size = size, pch = pch, gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "box", default = gpar(fill = clr.marker, 
                col = clr.marker)))
    }
}


 library(forestplot)
 tab_inc1 |>  group_by(group) |>
  forestplot::forestplot(fn.ci_norm=c(fpDrawNormalCI, fpDrawDiamondCI, fpDraw3CI, fpDrawCircleCI,fpDraw4CI), xlab = "IRR Estimates with 95% CI", boxsize=0.09, xlog=TRUE, xticks =  c(log(.125),log(0.25),log(0.5),0,log(2),log(4),log(8)),txt_gp = fpTxtGp(label=gpar(cex=.8),xlab=gpar(cex=.7), ticks=gpar(cex=.7), legend=gpar(cex=.7))) |> 
  fp_add_lines("steelblue") |> 
  fp_add_header("Variable") |> 
  fp_set_style(box = c("blue", "red","darkgreen","purple","orange"))  |>  fp_set_zebra_style("#F5F9F9") 
 
```





```{r}

patients_sum = d_inc_cw |> group_by(patient,program,male) |> summarize(time_os=sum(pys),cd4=last(cd4_rt_init_imp),art=max(art_ind), age_es=last(age), inc=max(ks_ind))


vars=c("Program, East Africa", "Sex, male", "Follow-up time", "ART experienced", "Age at study end","CD4 at study end")


p1=c(paste(round(table(patients_sum[patients_sum$inc==0,]$program)[[2]]/sum(table(patients_sum[patients_sum$inc==0,]$program)),3)*100, '%', sep = ""),paste(round(table(patients_sum[patients_sum$inc==0,]$male)[[2]]/sum(table(patients_sum[patients_sum$inc==0,]$male)),3)*100, '%', sep = ""),paste0(round(quantile(patients_sum[patients_sum$inc==0,]$time_os)[[3]],1)," ","(",round(quantile(patients_sum[patients_sum$inc==0,]$time_os)[[2]],1),", ", round(quantile(patients_sum[patients_sum$inc==0,]$time_os)[[4]],1),")"), paste(round(table(patients_sum[patients_sum$inc==0,]$art)[[2]]/sum(table(patients_sum[patients_sum$inc==0,]$art)),3)*100, '%', sep = ""),paste0(round(quantile(patients_sum[patients_sum$inc==0,]$age_es)[[3]],1)," ","(",round(quantile(patients_sum[patients_sum$inc==0,]$age_es)[[2]],1),", ", round(quantile(patients_sum[patients_sum$inc==0,]$age_es)[[4]],1),")"),paste0(round(quantile(patients_sum[patients_sum$inc==0,]$cd4)[[3]]^2,1)," ","(",round(quantile(patients_sum[patients_sum$inc==0,]$cd4)[[2]]^2,1),", ", round(quantile(patients_sum[patients_sum$inc==0,]$cd4)[[4]]^2,1),")"))

p2=c(paste(round(table(patients_sum[patients_sum$inc==1,]$program)[[2]]/sum(table(patients_sum[patients_sum$inc==1,]$program)),3)*100, '%', sep = ""),paste(round(table(patients_sum[patients_sum$inc==1,]$male)[[2]]/sum(table(patients_sum[patients_sum$inc==1,]$male)),3)*100, '%', sep = ""),paste0(round(quantile(patients_sum[patients_sum$inc==1,]$time_os)[[3]],1)," ","(",round(quantile(patients_sum[patients_sum$inc==1,]$time_os)[[2]],1),", ", round(quantile(patients_sum[patients_sum$inc==1,]$time_os)[[4]],1),")"), paste(round(table(patients_sum[patients_sum$inc==1,]$art)[[2]]/sum(table(patients_sum[patients_sum$inc==1,]$art)),3)*100, '%', sep = ""),paste0(round(quantile(patients_sum[patients_sum$inc==1,]$age_es)[[3]],1)," ","(",round(quantile(patients_sum[patients_sum$inc==1,]$age_es)[[2]],1),", ", round(quantile(patients_sum[patients_sum$inc==1,]$age_es)[[4]],1),")"),paste0(round(quantile(patients_sum[patients_sum$inc==1,]$cd4)[[3]]^2,1)," ","(",round(quantile(patients_sum[patients_sum$inc==1,]$cd4)[[2]]^2,1),", ", round(quantile(patients_sum[patients_sum$inc==1,]$cd4)[[4]]^2,1),")"))


v3=data.frame(vars,p1,p2)

ktab<-kable(v3,caption = "Characteristics of error-prone incidence cohort",booktabs=TRUE,col.names = c("Variable","Not incidenct (N=254,347)","Incident (N=803)"),linesep = "\\addlinespace")

kable_styling(ktab,full_width = F, font_size = 10,latex_options = "scale_down") |> add_footnote("Binary variables include percentages. Numeric variables include medians (25th and 75th percentiles).")


#ch_10= ch_9 |> left_join(d1[d1$V==1,c('patient','enrol_d_final')])
```




```{r}

#patients_sum = d_inc_cw |> filter(V==0) |> group_by(patient,program,male) |> summarize(time_os=sum(pys),cd4=last(cd4_rt_init_imp),art=max(art_ind), age_es=last(age), inc=max(ks_ind))


patients_sum1 = d_inc_cw |> filter(V==1) |> group_by(patient,program,male_final,w_est) |> summarize(time_os=sum(pys_final),cd4=last(cd4_rt_imp_final),art=max(art_ind_final), age_es=last(age_final), inc=max(ks_ind_final))

vars=c("Program, East Africa", "Sex, male", "Follow-up time", "ART experienced", "Age at study end","CD4 at study end")

p1=c(paste(round(weighted.mean(patients_sum1[patients_sum1$inc==0,]$program,patients_sum1[patients_sum1$inc==0,]$w_est),3)*100, '%', sep = ""),paste(round(weighted.mean(patients_sum1[patients_sum1$inc==0,]$male_final,patients_sum1[patients_sum1$inc==0,]$w_est),3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$time_os,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$time_os,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$time_os,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.75),1),")"),paste(round(weighted.mean(patients_sum1[patients_sum1$inc==0,]$art,patients_sum1[patients_sum1$inc==0,]$w_est)
,3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$age_es,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$age_es,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$age_es,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.75),1),")"),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$cd4,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.5)^2,1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$cd4,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.25)^2,1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==0,]$cd4,patients_sum1[patients_sum1$inc==0,]$w_est,prob=0.75)^2,1),")"))

p2=c(paste(round(weighted.mean(patients_sum1[patients_sum1$inc==1,]$program,patients_sum1[patients_sum1$inc==1,]$w_est),3)*100, '%', sep = ""),paste(round(weighted.mean(patients_sum1[patients_sum1$inc==1,]$male_final,patients_sum1[patients_sum1$inc==1,]$w_est),3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$time_os,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$time_os,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$time_os,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.75),1),")"),paste(round(weighted.mean(patients_sum1[patients_sum1$inc==1,]$art,patients_sum1[patients_sum1$inc==1,]$w_est)
,3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$age_es,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$age_es,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$age_es,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.75),1),")"),paste0(round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$cd4,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.5)^2,1)," ","(",round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$cd4,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.25)^2,1),", ", round(modi::weighted.quantile(patients_sum1[patients_sum1$inc==1,]$cd4,patients_sum1[patients_sum1$inc==1,]$w_est,prob=0.75)^2,1),")"))

v3=data.frame(vars,p1,p2)

ktab<-kable(v3,caption = "Characteristics of weighted incidence cohort",booktabs=TRUE,col.names = c("Variable","Not incident (N=632)","Incident (N=199)"),linesep = "\\addlinespace")

kable_styling(ktab,full_width = F, font_size = 10,latex_options = "scale_down") |> add_footnote("Binary variables include percentages. Numeric variables include medians (25th and 75th percentiles).")



```



```{r}
##############################################################################################################################
##############################################################################################################################

#### Overall unadjusted GR weighted incidence ####

##############################################################################################################################
##############################################################################################################################

### overall

mod_ehr_inc2 = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw, family = poisson) 

  #### Raking
  IF_func <- function(fit){
    MM <- model.matrix(fit)
    Score.P   <- fit$y*MM - MM*exp(fit$linear.predictors)
    InfoMat.P <- t(MM*sqrt(exp(fit$linear.predictors))) %*% (MM*sqrt(exp(fit$linear.predictors)))/nrow(MM)
    inffunc <- (Score.P) %*% solve(InfoMat.P)
    inffunc
  }    

naiveInfl3 =  IF_func(mod_ehr_inc2)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_inc_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
Ninflcal3<-calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_inc_2 = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3, family = poisson)

overall_inc_ci=exp(fit_gr_inc_2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2)))*1.96)
overall_inc_est=exp(fit_gr_inc_2[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (1.14 KS cases) per 1000 person-years

###############################################################################################################################

### Using the bootstrap to get 95% CI

##############################################################################################################################


# d15=d14[d14$V==1,]
# d15$w_gr=1/Ninflcal3$prob
# 
# set.seed(15)
# ests.boot<-NULL
# Nboot<-1000
# for (i in 1:Nboot) {
#   bootsamp<-sample(sort(unique(d15$patient)),length(unique(d15$patient)),replace=T)
#   dboot<-d15[d15$patient %in% bootsamp,]
#   designMF_boot = twophase(id=list(~1,~1),weights=list(~1,~w_gr), data=dboot,subset=~V==1,method="approx")
#   ests.boot[i]=svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=designMF_boot, family = poisson)$coefficients[[1]]
#   cat(i, "of 1000\r") 
#   flush.console()
# }
# 
# CI_boot<-quantile(ests.boot,c(.025,.975))
# exp(CI_boot)

################################################################################################################################
################################################################################################################################


### East Africa

mod_ehr_inc2_ea = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw[d_inc_cw$program==1,], family = poisson) 

naiveInfl3_ea =  IF_func(mod_ehr_inc2_ea)
colnames(naiveInfl3_ea)=paste("INF", 1:ncol(naiveInfl3_ea), sep="")

d14_ea=cbind(d_inc_cw[d_inc_cw$program==1,],naiveInfl3_ea) 

infs_eq1_ea <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3_ea), collapse = ' + ')))
designMF4_ea = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14_ea,subset=~V==1,method="approx")
Ninflcal3_ea<-calibrate(designMF4_ea,formula=infs_eq1_ea,phase=2,calfun="raking") 
fit_gr_inc_2_ea = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3_ea, family = poisson)

ea_inc_ci=exp(fit_gr_inc_2_ea[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2_ea)))*1.96)
ea_inc_est=exp(fit_gr_inc_2_ea[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (0.98 KS cases) per 1000 person-years
# 
# d15_ea=d14[d14$V==1 & d14$program==1,]
# d15_ea$w_gr=1/Ninflcal3_ea$prob
# 
# set.seed(15)
# ests.boot.ea<-NULL
# Nboot<-1000
# for (i in 1:Nboot) {
#   bootsamp<-sample(sort(unique(d15_ea$patient)),length(unique(d15_ea$patient)),replace=T)
#   dboot<-d15_ea[d15_ea$patient %in% bootsamp,]
#   designMF_boot = twophase(id=list(~1,~1),weights=list(~1,~w_gr), data=dboot,subset=~V==1,method="approx")
#   ests.boot.ea[i]=svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=designMF_boot, family = poisson)$coefficients[[1]]
#   cat(i, "of 1000\r") 
#   flush.console()
# }
# 
# CI_boot_ea<-quantile(ests.boot.ea,c(.025,.975))
# exp(CI_boot_ea)


### Latin America

mod_ehr_inc2_cn = glm(ks_ind ~ 1,offset = log(pys/1000),data= d_inc_cw[d_inc_cw$program==0,], family = poisson) 

naiveInfl3_cn =  IF_func(mod_ehr_inc2_cn)
colnames(naiveInfl3_cn)=paste("INF", 1:ncol(naiveInfl3_cn), sep="")

d14_cn=cbind(d_inc_cw[d_inc_cw$program==0,],naiveInfl3_cn) 

infs_eq1_cn <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3_cn), collapse = ' + ')))
designMF4_cn = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14_cn,subset=~V==1,method="approx")
Ninflcal3_cn<-calibrate(designMF4_cn,formula=infs_eq1_cn,phase=2,calfun="raking") 
fit_gr_inc_2_cn = svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=Ninflcal3_cn, family = poisson)

cn_inc_ci=exp(fit_gr_inc_2_cn[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_inc_2_cn)))*1.96)
cn_inc_est=exp(fit_gr_inc_2_cn[[1]])

### ^^^^^ exp(beta_0) is the incidence rate (2.86 KS cases) per 1000 person-years

# 
# d15_cn=d14[d14$V==1 & d14$program==0,]
# d15_cn$w_gr=1/Ninflcal3_cn$prob
# 
# set.seed(15)
# ests.boot.cn<-NULL
# Nboot<-1000
# for (i in 1:Nboot) {
#   bootsamp<-sample(sort(unique(d15_cn$patient)),length(unique(d15_cn$patient)),replace=T)
#   dboot<-d15_cn[d15_cn$patient %in% bootsamp,]
#   designMF_boot = twophase(id=list(~1,~1),weights=list(~1,~w_gr), data=dboot,subset=~V==1,method="approx")
#   ests.boot.cn[i]=svyglm(ks_ind_final ~ 1, offset = log(pys_final/1000), design=designMF_boot, family = poisson)$coefficients[[1]]
#   cat(i, "of 100\r") 
#   flush.console()
# }
# 
# CI_boot_cn<-quantile(ests.boot.cn,c(.025,.975))
# exp(CI_boot_cn)


Nmax <- 10000
mean_x <- rep(NA, Nmax)
x <- c()
for (i in 1:Nmax){
  x_1 <- rt(1, 2)
  x   <- c(x, x_1)
  mean_x[i] <- mean(x)
}
```