---
title: "KS Data"
author: "Josh"
output: html_document
---


```{r echo=FALSE}

library(dplyr)
library(dtplyr)
library(data.table)
library(splines)
library(survey)
library(mitools)
library(mvtnorm)
library(kableExtra)


load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cohort_imp1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4_1.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_cd4.Rda") 


#all_cd4_1 = all_cd4_1 |> filter(!is.na(month_avg_cd4))
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4.Rda") 
load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long4_1.Rda") 

patients_all = fread("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Sampling_frame/patients_all.csv")
names(patients_all)="patient"

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/all_val_long.Rda") 



all_val_long4$R=1

d_1 = all_cohort_imp1 |> filter(patient %in% all_val_long$patient)  |> left_join(all_val_long4[,c('patient','R')]) |> count(patient,stop_d,program,death_y,R) |> mutate(n=NULL,R=if_else(is.na(R),0,R))

cd4_df_val = all_val_long4_1 |> ungroup() |> select(patient,cd4_v_final,cd4_d_final) |> mutate(date=cd4_d_final)

cd4_df = all_cd4 |> ungroup() |> select(patient,cd4_v,cd4_d) |> mutate(date=cd4_d)

```


```{r}
#### Single imputation for filling in missing cd4 values in phase 1 and phase 2

#### use one row for all patients in cohort 
d = all_cohort_imp1 |> inner_join(patients_all,by="patient")  


##################################################################################################################################
##################################################################################################################################

## Remove patients w/ dis_d < as.Date("2009-12-01")
d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  

#d1 = d |> filter((V==0 & !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | V==0 & !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0) | V==1 & !is.na(dis_d) & !is.na(canc_d_final) & as.Date(canc_d_final)>=as.Date("2009-12-01"))

cd4_df1 = cd4_df |> lazy_dt() |> filter(patient %in% d1$patient)  |> left_join(d1[,c("patient","enrol_d")]) |> mutate(Diff=abs(cd4_d-as.Date(enrol_d))) |> group_by(patient) |> slice_min(Diff, with_ties = F) |> mutate(Diff=if_else(Diff<183,Diff,NA))  |> ungroup() |> as.data.frame()

d2= d1 |> left_join(cd4_df1[,c("patient","cd4_v","cd4_d","Diff")]) |> mutate(cd4_rt=if_else(!is.na(Diff),sqrt(cd4_v),NA))



## Add validated CD4 


cd4_df_val1 = cd4_df_val |> filter(patient %in% d1$patient)  |> left_join(d1[,c("patient","enrol_d_final")]) |> mutate(Diff_final=abs(cd4_d_final-as.Date(enrol_d_final))) |> group_by(patient) |> slice_min(Diff_final, with_ties = F) |> mutate(Diff_final=if_else(Diff_final<183,Diff_final,NA))

d3= d2 |> left_join(cd4_df_val1[,c("patient","cd4_v_final","cd4_d_final","Diff_final")]) |> mutate(cd4_rt_final=if_else(!is.na(Diff_final),sqrt(cd4_v_final),NA))

##################################################################################################################################
##################################################################################################################################
  
## Allow patients w/ dis_d >= as.Date("2009-12-01") for date shift from East Africa
# d1 = d |> filter(is.na(dis_d) | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2009-12-01") & program==1 | !is.na(dis_d) & as.Date(dis_d) >= as.Date("2010-01-01") & program==0)  
# 
# d1$enrol_d_year_month= format(as.Date(d1$enrol_d), "%Y-%m")
# 
# ## Add unvalidated CD4 
# d2 = d1 |> left_join(all_cd4_1[,c("patient","year_month","month_avg_cd4")],by="patient") |> mutate(cd4_d=if_else(!is.na(year_month),paste(year_month, "-01", sep=""),NA)) |>mutate(cd4_d=as.Date(cd4_d), Diff= cd4_d-as.Date(enrol_d)) |> mutate(Diff=if_else(Diff>-183,Diff,NA),Diff=abs(Diff))
# 
# ### limit to date of cd4 closest to enrollment (6 months before to 12 months after) 
# d3_1= d2|> group_by(patient) |> slice_min(Diff, with_ties = F) |> mutate(cd4_rt=if_else(!is.na(Diff) & !is.na(month_avg_cd4),sqrt(month_avg_cd4),NA))
# 
# 
# ## Add validated CD4 
# 
# d4 = d3_1 |> left_join(all_val_long4[,c("patient","month_avg_cd4_final","cd4_d_final")],by="patient") 
# 
# #d4_1 = d4|> mutate(Diff1= if_else(!is.na(cd4_d_final),cd4_d_final-enrol_d_final,NA))
# 
# d4$Diff1=d4$cd4_d_final - d4$enrol_d_final 
# d4$Diff1=ifelse(d4$Diff1 >-183,d4$Diff1,NA)
# d4$Diff1=abs(d4$Diff1)
# 
# #d4 = d4|> mutate(Diff1=if_else(Diff1>-183,Diff1,NA),Diff1=abs(Diff1))
#   
# d5= d4|> group_by(patient) |> slice_min(Diff1, with_ties = F) |> mutate(cd4_rt_final=if_else(!is.na(Diff1) & !is.na(month_avg_cd4_final),sqrt(month_avg_cd4_final),NA))


d6 = d3 |> lazy_dt() |>  mutate(age=as.numeric(round((as.Date(enrol_d)-as.Date(birth_d))/365.25,1)), year = if_else(as.Date(enrol_d)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(enrol_d,1,4))),art_ind = if_else(is.na(art_sd),0,if_else(as.Date(art_sd)<as.Date(enrol_d),1,0)),age_final=as.numeric(round((as.Date(enrol_d_final)-as.Date(birth_d_final))/365.25,1)), year_final = if_else(as.Date(enrol_d_final)<as.Date("2010-01-01"),
 as.numeric("2010"),as.numeric(substr(enrol_d_final,1,4))),art_ind_final = if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0))) |> ungroup() |> as.data.frame()

## KS indicator
d6 = d6 |> lazy_dt()|> mutate(ks_ind = if_else(!is.na(dis_d),1,0)) |> ungroup() |> as.data.frame()

## KS indicator validated (one patient had canc_d_final in 7/2009, make not KS diagnosis)
d6 = d6  |> lazy_dt()  |> mutate(ks_ind_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final),1,0))) |> ungroup() |> as.data.frame()

#############################################################################################################################
#### prevalence indicator
## KS indicator
d6 = d6 |> lazy_dt() |> mutate(prevalent = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60 & dis_d >= enrol_d - 60,1,0)) |> mutate(prevalent_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60 & canc_d_final >= enrol_d_final - 60,1,0))) |> ungroup() |> as.data.frame()

## remove KS cases >60 days before enrollment (54 instances between phase 1 and phase2)
d6 = d6 |> mutate(remove=if_else((!is.na(canc_d_final) & canc_d_final < enrol_d_final - 60) | (!is.na(dis_d) & dis_d < enrol_d - 60),1,0)) |> filter(remove==0)

###############################################

 
d6 = d6  |> lazy_dt() |> filter(as.Date(enrol_d)>=as.Date("2010-01-01") | (as.Date(enrol_d)>=as.Date("2009-12-01") & program==1)) |> filter(V==0 | (V==1 & (as.Date(enrol_d_final)>=as.Date("2010-01-01") | (as.Date(enrol_d_final)>=as.Date("2009-12-01") & program==1)))) |> ungroup() |> as.data.frame()



```


```{r}
# MI error prone w/o MI eligibility
m=10
set.seed(1993)
betas_ipw_prev1 = vcovs_ipw_prev1 = betas_gr_mi_prev1 = vcovs_gr_mi_prev1 = naiveInfl = dat = betas_gr_mi_prev2 = vcovs_gr_mi_prev2 = betas_ehr_prev1 = vcovs_ehr_prev1= vector("list", m)

for(i in 1:m){
##### Multiple imputation for cd4_rt in phase 1 AND 2

    ### imputation for phase 1 cd4 values based on error prone variables
    mod5 = lm(cd4_rt ~  male +program+ ns(age,df=4)+ year+art_ind +prevalent, data= d6) 
    #ch=d6[!is.na(d6$cd4_rt),]
   ## to easily get design matrix for the full cohort
    d6_1 = d6 |> mutate(cd4_rt=1)
    v3=model.matrix(terms(mod5),d6_1)
    beta2 = mod5$coefficients
    vcov2 = vcov(mod5)
    rmvs2=rmvnorm(n=1,beta2,vcov2)
    rmvs2 = as.vector(rmvs2)
    cd4_rt_new = as.vector((v3 %*% rmvs2) + sample(resid(mod5),1))
    d6$cd4_rt_init_imp=if_else(is.na(d6$cd4_rt),cd4_rt_new,d6$cd4_rt)
    ### any imputed CD4<0 assign a 1
    d6$cd4_rt_init_imp=if_else(d6$cd4_rt_init_imp<0,1,d6$cd4_rt_init_imp)

  ### imputation for phase 2 cd4 values
  
  mod6 = lm(cd4_rt_final ~  male_final +program+ ns(age_final,df=4) + ns(cd4_rt_init_imp,df=4) + year_final +art_ind_final +prevalent_final, data= d6[d6$V==1,])
    ## to easily get design matrix for phase 2
  d6_1 = d6[d6$V==1,] |> mutate(cd4_rt_final=1)
   v4=model.matrix(terms(mod6),d6_1)
  beta2 = mod6$coefficients
  vcov2 = vcov(mod6)
  rmvs2=rmvnorm(n=1,beta2,vcov2)
  rmvs2 = as.vector(rmvs2)
  cd4_rt_final_new = as.vector((v4 %*% rmvs2) + sample(resid(mod6),1))
  d6_phase2 = d6[d6$V==1,]
  d6_phase2$cd4_rt_imp_final=if_else(is.na(d6_phase2$cd4_rt_final),cd4_rt_final_new,d6_phase2$cd4_rt_final)
  
  d6_phase1 = d6 |> filter(V!=1) |> mutate(cd4_rt_imp_final=NA)
  
  d7 = rbind(d6_phase1,d6_phase2) 


# #############################################################################################################################
# #### prevalence indicator
# ## KS indicator
# d7 = d7 |> mutate(prevalent = if_else(!is.na(dis_d) & dis_d <= enrol_d + 60,1,0)) |> mutate(prevalent_final = if_else(V==0,NA, if_else(V==1 & !is.na(canc_d_final) & canc_d_final <= enrol_d_final + 60,1,0)))
#   
#  
# d8 = d7 |> filter(as.Date(enrol_d)>=as.Date("2010-01-01") | (as.Date(enrol_d)>=as.Date("2009-12-01") & program==1)) |> filter(V==0 | (V==1 & (as.Date(enrol_d_final)>=as.Date("2010-01-01") | (as.Date(enrol_d_final)>=as.Date("2009-12-01") & program==1))))


### keep incident cases and mark prevalent==0 
#d8|> filter(ks_y==1 & prevalent==0) |> View()

d_2 = d_1 |> filter(patient %in% d7$patient)
mod_w = glm(R ~ stop_d + program + death_y, family=binomial,data = d_2)
mod_p<- mod_w$fitted.values
d_p = data.frame(d_2,p_est=mod_p)


#################################################################################################################  
#### IPW with original design weights for the entire sample frame
#load(file="~/Desktop/PhD/Research/KS_Data/Code/wgts_by_hand.Rda")

load(file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/strata.Rda")

## nonresponse probabilities
#load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/Base_data/d_p.Rda") 

#d_prev_c= merge(x=d7,y=d3,all.x=TRUE,by="patient")
d_prev_c= merge(x=d7,y=d_c2,all.x=TRUE,by="patient")

### collapsing strata so we can use them in twophase() to estimate correct variance (strata_new)
d_prev_c= merge(x=d_prev_c,y=d_p[,c('patient','p_est')],all.x=TRUE,by="patient") |> mutate(strata_new=if_else(strata %in% c("HN KS 2010-2019","HN No KS"),"HN",if_else(strata %in% c("MX-INCMNSZ KS 2010-2014","MX-INCMNSZ KS 2015-2019"),"MX KS",strata)))

#################################################################################################################
#### IPW with estimated weights including nonresponse probabilities from the prevalence at enrollment analysis cohort

#mod_w = glm(V ~ strata, family=binomial,data = d_prev_c)
mod_w = glm(V ~ strata_new, family=binomial,data = d_prev_c)

mod_p <- mod_w$fitted.values
d_prev_cw = data.frame(d_prev_c,p_est_overall=mod_p)
d_prev_cw = d_prev_cw |> mutate(w_est = 1/(p_est_overall*p_est)) 

designMF6 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new),subset=~V==1, data=d_prev_cw,method="approx")
#designMF6 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata),subset=~V==1, data=d_prev_cw,method="approx")
#designMF6 = twophase(id=list(~1,~1),weights=list(~1,~w_est),subset=~V==1, data=d_prev_cw,method="approx")

ipw_prev_c2 = svyglm(prevalent_final ~ male_final + program + I(age_final/10) + I(year_final-2010) + art_ind_final + cd4_rt_imp_final, design=designMF6, family = quasibinomial())

#save(d_prev_cw,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/prevalence_data_stabilized_weights_v1.Rda")   

#################################################################################################################
##### Generalized raking

#### 4 patients were removed from phase 2 because their enrol_d < 2010 but enrol_d_final > 2010
#d7_ehr1 = d7_ehr |> filter(V==0 | (V==1 & (as.Date(enrol_d_final)>=as.Date("2010-01-01") | (as.Date(enrol_d_final)>=as.Date("2009-12-01") & program==1))))


mod_ehr_prev = glm(prevalent ~ male+program+I(age/10)+I(year-2010)+art_ind + cd4_rt_init_imp, data= d_prev_cw, family = binomial)

#######  w/o intercept in gr calibration, just considering efficiency for coef. ests. 
## Tong's function
inf.fun <- function(fit) {
  dm <- model.matrix(fit)
  Ihat <- (t(dm) %*% (dm * fit$fitted.values * (1 - fit$fitted.values))) / nrow(dm)
  ## influence function
  infl <- (dm * resid(fit, type = "response")) %*% solve(Ihat)
  infl
}

naiveInfl3 =  inf.fun(mod_ehr_prev)[,-1]
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))

#designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est), data=d14,subset=~V==1,method="approx")
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")

Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ male_final + program + I(age_final/10) + I(year_final-2010) + art_ind_final + cd4_rt_imp_final, design=Ninflcal3, family = quasibinomial())

betas_ipw_prev1[[i]] = coef(ipw_prev_c2)
vcovs_ipw_prev1[[i]] = vcov(ipw_prev_c2)
betas_gr_mi_prev1[[i]] = coef(fit_gr_prev2)
vcovs_gr_mi_prev1[[i]] = vcov(fit_gr_prev2)
betas_ehr_prev1[[i]] = coef(mod_ehr_prev)
vcovs_ehr_prev1[[i]] = vcov(mod_ehr_prev)
}

wgt_prev_results1=MIcombine(betas_ipw_prev1,vcovs_ipw_prev1)
rak_prev_results1=MIcombine(betas_gr_mi_prev1,vcovs_gr_mi_prev1)
ehr_prev_results1=MIcombine(betas_ehr_prev1,vcovs_ehr_prev1)


save(wgt_prev_results1,rak_prev_results1,ehr_prev_results1,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_error_prone_nr_elig1.Rda") 
```



```{r}
# Multiple imputation for measurement error correction
m=10
betas_mi_prev = vcovs_mi_prev = vector("list", m)

for(i in 1:m){
  
d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/overall_ppv_npv/ks_mi_",i,".csv"))

#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/by_site/ks_mi_",i,".csv"))

#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/overall_no_ks/ks_mi_",i,".csv"))


#d10=fread(paste0("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_datasets/ch/ks_mi_",i,".csv"))


# d_prev = d10 |> lazy_dt() |> filter(as.Date(enrol_d_imp)>=as.Date("2010-01-01") | (as.Date(enrol_d_imp)>=as.Date("2009-12-01") & program==1)) |> 
#   group_by(patient) |> mutate(ks_d_imp=if_else(cumsum(ks_ind_imp)==1 & is.na(canc_d_final),as.Date(paste(year_month, "-01", sep="")),if_else(!is.na(canc_d_final),as.Date(canc_d_final),NA))) |> 
#   mutate(prevalent = if_else(is.na(ks_d_imp),0,if_else(as.Date(ks_d_imp) <= as.Date(enrol_d_imp) + 60,1,0))) |> 
#   filter(enrol_d_imp_year_month==year_month | (row_number() ==1 & enrol_d_imp_year_month=="2009-12")) |> mutate(year_imp = as.numeric(substr(year_month,1,4)) ) |> 
#   mutate(age1= age_imp ,year1=year_imp,art_ind1=if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0)),cd4_rt_imp_final1=cd4_rt_imp_final) |> ungroup() |> as.data.frame()

# # 
# d_prev = d10 |> lazy_dt() |> filter(as.Date(enrol_d_imp)>=as.Date("2010-01-01") | (as.Date(enrol_d_imp)>=as.Date("2009-12-01") & program==1)) |>
#   group_by(patient) |> mutate(ks_d_imp=if_else(cumsum(ks_ind_imp)==1 & is.na(canc_d_final),as.Date(paste(year_month, "-01", sep="")),if_else(!is.na(canc_d_final),as.Date(canc_d_final),NA))) |> filter(as.Date(ks_d_imp) >= as.Date(enrol_d_imp) - 60) |>
#   mutate(prevalent = if_else(is.na(ks_d_imp),0,if_else(as.Date(ks_d_imp) <= as.Date(enrol_d_imp) + 60 & as.Date(ks_d_imp) >= as.Date(enrol_d_imp) - 60,1,0))) |>
#   filter(enrol_d_imp_year_month==year_month | (row_number() ==1 & enrol_d_imp_year_month=="2009-12")) |> mutate(year_imp = as.numeric(substr(year_month,1,4)) ) |>
#   mutate(age1= age_imp ,year1=year_imp,art_ind1=if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0)),cd4_rt_imp_final1=cd4_rt_imp_final) |> ungroup() |> as.data.frame()
# 
# ### no enrollment imp with ks imp
# # 
# d_prev = d10 |> lazy_dt() |> filter(as.Date(enrol_d1)>=as.Date("2010-01-01") | (as.Date(enrol_d1)>=as.Date("2009-12-01") & program==1)) |>
#   group_by(patient) |> mutate(ks_d_imp=if_else(cumsum(ks_ind_imp)==1 & is.na(canc_d_final),as.Date(paste(year_month, "-01", sep="")),if_else(!is.na(canc_d_final),as.Date(canc_d_final),NA))) |> filter(as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60) |>
#   mutate(prevalent = if_else(is.na(ks_d_imp),0,if_else(as.Date(ks_d_imp) <= as.Date(enrol_d1) + 60 & as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60,1,0))) |>
#   filter(enrol_d1_year_month==year_month | (row_number() ==1 & enrol_d1_year_month=="2009-12")) |> mutate(year_imp = as.numeric(substr(year_month,1,4)) ) |>
#   mutate(age1= age_imp ,year1=year_imp,art_ind1=if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0)),cd4_rt_imp_final1=cd4_rt_imp_final) |> ungroup() |> as.data.frame()


### 
d_prev = d10 |> lazy_dt() |> filter(as.Date(enrol_d1)>=as.Date("2010-01-01") | (as.Date(enrol_d1)>=as.Date("2009-12-01") & program==1)) |>
  group_by(patient) |> mutate(ks_d_imp=if_else(cumsum(ks_ind_imp)==1 & is.na(canc_d_final),as.Date(paste(year_month, "-01", sep="")),if_else(!is.na(canc_d_final),as.Date(canc_d_final),NA))) |> filter(as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60) |>
  mutate(prevalent = if_else(is.na(ks_d_imp),0,if_else(as.Date(ks_d_imp) <= as.Date(enrol_d1) + 60 & as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60,1,0))) |>
  filter(enrol_d1_year_month==year_month | (row_number() ==1 & enrol_d1_year_month=="2009-12")) |> mutate(year_imp = as.numeric(substr(year_month,1,4)) ) |>
  mutate(age1= age_imp ,year1=year_imp,art_ind1=if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0)),cd4_rt_imp_final1=cd4_rt_imp_final) |> ungroup() |> as.data.frame()

### no enrollment imp without ks imp
# 
# d_prev = d10 |> lazy_dt() |> filter(as.Date(enrol_d1)>=as.Date("2010-01-01") | (as.Date(enrol_d1)>=as.Date("2009-12-01") & program==1)) |> 
#   group_by(patient) |> mutate(ks_d_imp=if_else(cumsum(ks_ind)==1 & is.na(canc_d_final),as.Date(paste(year_month, "-01", sep="")),if_else(!is.na(canc_d_final),as.Date(canc_d_final),NA))) |> filter(as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60) |> 
#   mutate(prevalent = if_else(is.na(ks_d_imp),0,if_else(as.Date(ks_d_imp) <= as.Date(enrol_d1) + 60 & as.Date(ks_d_imp) >= as.Date(enrol_d1) - 60,1,0))) |> 
#   filter(enrol_d1_year_month==year_month | (row_number() ==1 & enrol_d1_year_month=="2009-12")) |> mutate(year_imp = as.numeric(substr(year_month,1,4)) ) |> 
#   mutate(age1= age_imp ,year1=year_imp,art_ind1=if_else(is.na(recart_d_final),0,if_else(as.Date(recart_d_final)<as.Date(enrol_d_final),1,0)),cd4_rt_imp_final1=cd4_rt_imp_final) |> ungroup() |> as.data.frame()

## MI

fit_mi_prev = glm(prevalent ~ male_imp + program + I(age_imp/10) + year_imp + art_ind_imp + cd4_rt_imp, data= d_prev, family = binomial) 

betas_mi_prev[[i]] = coef(fit_mi_prev)
vcovs_mi_prev[[i]] = vcov(fit_mi_prev)
}

#mi_prev_results1=MIcombine(betas_mi_prev,vcovs_mi_prev)
mi_prev_results2=MIcombine(betas_mi_prev,vcovs_mi_prev)


mi_prev_results=MIcombine(betas_mi_prev,vcovs_mi_prev)

save(wgt_prev_results1,rak_prev_results1,ehr_prev_results1,mi_prev_results1,mi_prev_results2,file="/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_error_prone1_nr_elig.Rda") 

load("/Users/joshslone/Library/CloudStorage/OneDrive-Vanderbilt/KS_MI_datasets/MI_error_prone1_nr_elig.Rda") 

```



```{r}

### CHECK AND FORMAT RESULTS FROM THE 3 ANALYSES!!!


lst= list(wgt_prev_results1,rak_prev_results1,ehr_prev_results1,mi_prev_results2,mi_prev_results1)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients[-1]
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0))[-1])), betas + 1.96*(sqrt(diag(vcov(res0))[-1])))
  res2[[j]] <- exp(cis3)
}


ktab9 = cbind(OR = format(round(res2[[1]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),
              OR = format(round(res2[[2]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),
              OR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)),OR = format(round(res2[[4]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[4]][,2],2),nsmall=2)," - ",format(round(res2[[4]][,3],2),nsmall=2)),OR = format(round(res2[[5]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[5]][,2],2),nsmall=2)," - ",format(round(res2[[5]][,3],2),nsmall=2)))


rownames(ktab9)=c('Male sex','East Africa','Age at enrollment x 10 years','Year of enrollment','ART before enrollment','Sq. rt. CD4 at enrollment')
ktab9 <- kable(ktab9,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","IPW" = 2,"GR" = 2,"EHR" = 2,"MI KS Overall" = 2,"MI KS by Site" = 2))


```

```{r}

### CHECK AND FORMAT RESULTS FROM THE 3 ANALYSES!!!


lst= list(wgt_prev_results1,rak_prev_results1,ehr_prev_results1)
res2=list()
### FORMATTING RESULTS

for (j in 1:length(lst)){
  res0 <- lst[[j]]
  
  betas <- res0$coefficients[-1]
  
  cis3<- cbind(betas, betas - 1.96*(sqrt(diag(vcov(res0))[-1])), betas + 1.96*(sqrt(diag(vcov(res0))[-1])))
  res2[[j]] <- exp(cis3)
}


ktab9 = cbind(OR = format(round(res2[[1]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[1]][,2],2),nsmall=2)," - ",format(round(res2[[1]][,3],2),nsmall=2)),
              OR = format(round(res2[[2]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[2]][,2],2),nsmall=2)," - ",format(round(res2[[2]][,3],2),nsmall=2)),
              OR = format(round(res2[[3]][,1],2),nsmall=2), CI_95_percent = paste0(format(round(res2[[3]][,2],2),nsmall=2)," - ",format(round(res2[[3]][,3],2),nsmall=2)))


rownames(ktab9)=c('Male sex','East Africa','Age at enrollment x 10 years','Year of enrollment','ART before enrollment','Sq. rt. CD4 at enrollment')
ktab9 <- kable(ktab9,booktabs=T)
kable_styling(ktab9,full_width = F, font_size = 10,latex_options="scale_down")%>%add_header_above(c(" ","IPW" = 2,"GR" = 2,"EHR" = 2))

```


```{r}

tab_prev1 = data.frame(labeltext=c("Male sex","Male sex","Male sex","Male sex","Male sex","East Africa","East Africa","East Africa","East Africa","East Africa","Age at enrollment x 10 years","Age at enrollment x 10 years","Age at enrollment x 10 years","Age at enrollment x 10 years","Age at enrollment x 10 years","Year of enrollment","Year of enrollment","Year of enrollment","Year of enrollment","Year of enrollment","ART before enrollment","ART before enrollment","ART before enrollment","ART before enrollment","ART before enrollment","CD4 (sq. root) at enrollment","CD4 (sq. root) at enrollment","CD4 (sq. root) at enrollment","CD4 (sq. root) at enrollment","CD4 (sq. root) at enrollment"),mean=c(res2[[1]][1],res2[[2]][1],res2[[3]][1],res2[[4]][1],res2[[5]][1],res2[[1]][2],res2[[2]][2],res2[[3]][2],res2[[4]][2],res2[[5]][2],res2[[1]][3],res2[[2]][3],res2[[3]][3],res2[[4]][3],res2[[5]][3],res2[[1]][4],res2[[2]][4],res2[[3]][4],res2[[4]][4],res2[[5]][4],res2[[1]][5],res2[[2]][5],res2[[3]][5],res2[[4]][5],res2[[5]][5],res2[[1]][6],res2[[2]][6],res2[[3]][6],res2[[4]][6],res2[[5]][6]), lower=c(res2[[1]][7],res2[[2]][7],res2[[3]][7],res2[[4]][7],res2[[5]][7],res2[[1]][8],res2[[2]][8],res2[[3]][8],res2[[4]][8],res2[[5]][8],res2[[1]][9],res2[[2]][9],res2[[3]][9],res2[[4]][9],res2[[5]][9],res2[[1]][10],res2[[2]][10],res2[[3]][10],res2[[4]][10],res2[[5]][10],res2[[1]][11],res2[[2]][11],res2[[3]][11],res2[[4]][11],res2[[5]][11],res2[[1]][12],res2[[2]][12],res2[[3]][12],res2[[4]][12],res2[[5]][12]),upper=c(res2[[1]][13],res2[[2]][13],res2[[3]][13],res2[[4]][13],res2[[5]][13],res2[[1]][14],res2[[2]][14],res2[[3]][14],res2[[4]][14],res2[[5]][14],res2[[1]][15],res2[[2]][15],res2[[3]][15],res2[[4]][15],res2[[5]][15],res2[[1]][16],res2[[2]][16],res2[[3]][16],res2[[4]][16],res2[[5]][16],res2[[1]][17],res2[[2]][17],res2[[3]][17],res2[[4]][17],res2[[5]][17],res2[[1]][18],res2[[2]][18],res2[[3]][18],res2[[4]][18],res2[[5]][18]),group=c("IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site","IPW", "GR", "EHR","MI KS Overall","MI KS by Site"))


fpDraw3CI = function (lower_limit, estimate, upper_limit, size, y.offset = 0.5, 
    clr.line, clr.marker, lwd, lty = 1, vertices, vertices.height = 0.1, 
    pch = 8, shapes_gp = fpShapesGp(), shape_coordinates = structure(c(1, 
        1), max.coords = c(1, 1)), ...) 
{
    if (is.na(lower_limit) || is.na(estimate) || is.na(upper_limit)) {
        return()
    }
    forestplot:::prFpDrawLine(lower_limit = lower_limit, upper_limit = upper_limit, 
        line_gp = prGetShapeGp(shapes_gp, shape_coordinates, 
            "lines", default = forestplot:::prDefaultGp(col = clr.line, lwd = lwd, 
                lty = lty)), vertices_gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "vertices", nodefault = TRUE), 
        y.offset = y.offset, vertices = vertices, vertices.height = vertices.height)
    box <- convertX(unit(estimate, "native"), "npc", valueOnly = TRUE)
    if (box >= 0 && box <= 1) {
        if (!is.unit(size)) {
            size <- unit(size, "snpc")
        }
        grid.points(x = unit(estimate, "native"), y = unit(y.offset, 
            "npc"), size = size, pch = pch, gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "box", default = gpar(fill = clr.marker, 
                col = clr.marker)))
    }
}


fpDraw4CI = function (lower_limit, estimate, upper_limit, size, y.offset = 0.5, 
    clr.line, clr.marker, lwd, lty = 1, vertices, vertices.height = 0.1, 
    pch = 24, shapes_gp = fpShapesGp(), shape_coordinates = structure(c(1, 
        1), max.coords = c(1, 1)), ...) 
{
    if (is.na(lower_limit) || is.na(estimate) || is.na(upper_limit)) {
        return()
    }
    forestplot:::prFpDrawLine(lower_limit = lower_limit, upper_limit = upper_limit, 
        line_gp = prGetShapeGp(shapes_gp, shape_coordinates, 
            "lines", default = forestplot:::prDefaultGp(col = clr.line, lwd = lwd, 
                lty = lty)), vertices_gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "vertices", nodefault = TRUE), 
        y.offset = y.offset, vertices = vertices, vertices.height = vertices.height)
    box <- convertX(unit(estimate, "native"), "npc", valueOnly = TRUE)
    if (box >= 0 && box <= 1) {
        if (!is.unit(size)) {
            size <- unit(size, "snpc")
        }
        grid.points(x = unit(estimate, "native"), y = unit(y.offset, 
            "npc"), size = size, pch = pch, gp = prGetShapeGp(shapes_gp, 
            shape_coordinates, "box", default = gpar(fill = clr.marker, 
                col = clr.marker)))
    }
}

library(forestplot)
 tab_prev1 |>  group_by(group) |>
  forestplot::forestplot(fn.ci_norm=c(fpDrawNormalCI, fpDrawDiamondCI, fpDraw3CI, fpDrawCircleCI,fpDraw4CI), xlab = "OR Estimates with 95% CI", boxsize=0.09, xlog=TRUE, xticks =  c(log(.125),log(0.25),log(0.5),0,log(2),log(4),log(8)),txt_gp = fpTxtGp(label=gpar(cex=.8),xlab=gpar(cex=.7), ticks=gpar(cex=.7), legend=gpar(cex=.7))) |> 
  fp_add_lines("steelblue") |> 
  fp_add_header("Variable") |> 
  fp_set_style(box = c("blue", "red","darkgreen","purple","orange"))  |>  fp_set_zebra_style("#F5F9F9") 
 
 
```



```{r}


vars=c("Program, East Africa", "Sex, male", "Year of enrollment", "ART before enrollment", "Age at enrollment","CD4 at enrollment")


p1=c(paste(round(table(d7[d7$prevalent==0,]$program)[[2]]/sum(table(d7[d7$prevalent==0,]$program)),3)*100, '%', sep = ""),paste(round(table(d7[d7$prevalent==0,]$male)[[2]]/sum(table(d7[d7$prevalent==0,]$male)),3)*100, '%', sep = ""),paste0(quantile(d7[d7$prevalent==0,]$year)[[3]]," ","(",quantile(d7[d7$prevalent==0,]$year)[[2]],", ", quantile(d7[d7$prevalent==0,]$year)[[4]],")"), paste(round(table(d7[d7$prevalent==0,]$art_ind)[[2]]/sum(table(d7[d7$prevalent==0,]$art_ind)),3)*100, '%', sep = ""),paste0(round(quantile(d7[d7$prevalent==0,]$age)[[3]],1)," ","(",round(quantile(d7[d7$prevalent==0,]$age)[[2]],1),", ", round(quantile(d7[d7$prevalent==0,]$age)[[4]],1),")"),paste0(round(quantile(d7[d7$prevalent==0,]$cd4_rt_init_imp)[[3]]^2,1)," ","(",round(quantile(d7[d7$prevalent==0,]$cd4_rt_init_imp)[[2]]^2,1),", ", round(quantile(d7[d7$prevalent==0,]$cd4_rt_init_imp)[[4]]^2,1),")"))

p2=c(paste(round(table(d7[d7$prevalent==1,]$program)[[2]]/sum(table(d7[d7$prevalent==1,]$program)),3)*100, '%', sep = ""),paste(round(table(d7[d7$prevalent==1,]$male)[[2]]/sum(table(d7[d7$prevalent==1,]$male)),3)*100, '%', sep = ""),paste0(quantile(d7[d7$prevalent==1,]$year)[[3]]," ","(",quantile(d7[d7$prevalent==1,]$year)[[2]],", ", quantile(d7[d7$prevalent==1,]$year)[[4]],")"), paste(round(table(d7[d7$prevalent==1,]$art_ind)[[2]]/sum(table(d7[d7$prevalent==1,]$art_ind)),3)*100, '%', sep = ""),paste0(round(quantile(d7[d7$prevalent==1,]$age)[[3]],1)," ","(",round(quantile(d7[d7$prevalent==1,]$age)[[2]],1),", ", round(quantile(d7[d7$prevalent==1,]$age)[[4]],1),")"),paste0(round(quantile(d7[d7$prevalent==1,]$cd4_rt_init_imp)[[3]]^2,1)," ","(",round(quantile(d7[d7$prevalent==1,]$cd4_rt_init_imp)[[2]]^2,1),", ", round(quantile(d7[d7$prevalent==1,]$cd4_rt_init_imp)[[4]]^2,1),")"))


v3=data.frame(vars,p1,p2)

ktab<-kable(v3,caption = "Characteristics of error-prone prevalence at enrollment cohort",booktabs=TRUE,col.names = c("Variable","Not prevalent (N=176,189)","Prevalent (N=1,404)"),linesep = "\\addlinespace")

kable_styling(ktab,full_width = F, font_size = 10,latex_options = "scale_down") |> add_footnote("Binary variables include percentages. Numeric variables include medians (25th and 75th percentiles).")



```



```{r}

d_prev11=d_prev_cw[d_prev_cw$V==1,]

vars=c("Program, East Africa", "Sex, male", "Year of enrollment", "ART before enrollment", "Age at enrollment","CD4 at enrollment")

p1=c(paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==0,]$program,d_prev11[d_prev11$prevalent_final==0,]$w_est),3)*100, '%', sep = ""),paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==0,]$male_final,d_prev11[d_prev11$prevalent_final==0,]$w_est),3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$year_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$year_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$year_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.75),1),")"),paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==0,]$art_ind_final,d_prev11[d_prev11$prevalent_final==0,]$w_est)
,3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$age_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$age_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$age_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.75),1),")"),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.5)^2,1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.25)^2,1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==0,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==0,]$w_est,prob=0.75)^2,1),")"))

p2=c(paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==1,]$program,d_prev11[d_prev11$prevalent_final==1,]$w_est),3)*100, '%', sep = ""),paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==1,]$male_final,d_prev11[d_prev11$prevalent_final==1,]$w_est),3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$year_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$year_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$year_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.75),1),")"),paste(round(weighted.mean(d_prev11[d_prev11$prevalent_final==1,]$art_ind_final,d_prev11[d_prev11$prevalent_final==1,]$w_est)
,3)*100, '%', sep = ""),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$age_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.5),1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$age_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.25),1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$age_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.75),1),")"),paste0(round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.5)^2,1)," ","(",round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.25)^2,1),", ", round(modi::weighted.quantile(d_prev11[d_prev11$prevalent_final==1,]$cd4_rt_imp_final,d_prev11[d_prev11$prevalent_final==1,]$w_est,prob=0.75)^2,1),")"))

v3=data.frame(vars,p1,p2)

ktab<-kable(v3,caption = "Characteristics of weighted prevalence at enrollment cohort",booktabs=TRUE,col.names = c("Variable","Not prevalent (N=176,189)","Prevalent (N=1,458)"),linesep = "\\addlinespace")

kable_styling(ktab,full_width = F, font_size = 10,latex_options = "scale_down") |> add_footnote("Binary variables include percentages. Numeric variables include medians (25th and 75th percentiles).")



```





```{r}

##############################################################################################################################
##############################################################################################################################

#### Overall unadjusted GR weighted prevalence ####

##############################################################################################################################
##############################################################################################################################
# 
# ### overall


mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw, family = binomial)

#######  w/o intercept in gr calibration, just considering efficiency for coef. ests. 
## Tong's function
inf.fun <- function(fit) {
  dm <- model.matrix(fit)
  Ihat <- (t(dm) %*% (dm * fit$fitted.values * (1 - fit$fitted.values))) / nrow(dm)
  ## influence function
  infl <- (dm * resid(fit, type = "response")) %*% solve(Ihat)
  infl
}

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw,naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and proability similar because of rare event)
overall_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
overall_prev_ci_prob=overall_prev_ci_odds/(1+overall_prev_ci_odds)
overall_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))

#   svydes_wgtb1 <- svydesign(id = ~patient, weights = ~w_est, data = d_prev11)
#   totals1 <- c('(Intercept)'=nrow(d_prev_cw), prevalent=sum(d_prev_cw$prevalent))
# 
#   svydes_cal1 <- survey::calibrate(svydes_wgtb1, formula = ~prevalent,
#                                    calfun = "raking", population = totals1)
#     
#   calibrated_prev_total=svytotal(~prevalent_final,svydes_cal1)
  # calibrated_prev_total[[1]]/nrow(d_prev_cw)
  # ci=calibrated_prev_total[[1]] + c(-1,1)*1.96* 30.896
  # ci/nrow(d_prev_cw)

  
### by region
  
#### East Africa
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$program==1,], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$program==1,],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and probability similar because of rare event)
ea_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
ea_prev_ci_prob=ea_prev_ci_odds/(1+ea_prev_ci_odds)
ea_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))
  
  
  
  # 
  # svydes_wgtb1_ea <- svydesign(id = ~patient, weights = ~w_est, data = d_prev11[d_prev11$program==1,])
  # totals1_ea <- c('(Intercept)'=nrow(d_prev_cw[d_prev_cw$program==1,]), prevalent=sum(d_prev_cw[d_prev_cw$program==1,]$prevalent))
  # 
  # svydes_cal1_ea <- survey::calibrate(svydes_wgtb1_ea, formula = ~prevalent,
  #                                  calfun = "raking", population = totals1_ea)
  #   
  # calibrated_prev_total_ea=svytotal(~prevalent_final,svydes_cal1_ea)
  

#calibrated_prev_total_ea[[1]]/nrow(d_prev_cw[d_prev_cw$program==1,])

#ci1=calibrated_prev_total_ea+c(-1,1)*1.96*29.285
#ci1/nrow(d_prev_cw[d_prev_cw$program==1,])

#### Latin America
  
mod_ehr_prev = glm(prevalent ~ 1, data= d_prev_cw[d_prev_cw$program==0,], family = binomial)

naiveInfl3 =  inf.fun(mod_ehr_prev)
colnames(naiveInfl3)=paste("INF", 1:ncol(naiveInfl3), sep="")

d14=cbind(d_prev_cw[d_prev_cw$program==0,],naiveInfl3) 

infs_eq1 <- as.formula(paste('~', paste0('INF', 1:ncol(naiveInfl3), collapse = ' + ')))
designMF4 = twophase(id=list(~1,~1),weights=list(~1,~w_est),strata=list(NULL,~strata_new), data=d14,subset=~V==1,method="approx")
Ninflcal3<-survey::calibrate(designMF4,formula=infs_eq1,phase=2,calfun="raking") 
fit_gr_prev2 = svyglm(prevalent_final ~ 1, design=Ninflcal3, family = quasibinomial())

### odds scale (and probability similar because of rare event)
cn_prev_ci_odds=exp(fit_gr_prev2[[1]]+c(-1,1)*sqrt(diag(vcov(fit_gr_prev2)))*1.96)
cn_prev_ci_prob=cn_prev_ci_odds/(1+cn_prev_ci_odds)
cn_prev_est=exp(fit_gr_prev2[[1]])/(1+exp(fit_gr_prev2[[1]]))
  
  # 
  # svydes_wgtb1_cn <- svydesign(id = ~patient, weights = ~w_est, data = d_prev11[d_prev11$program==0,])
  # totals1_cn <- c('(Intercept)'=nrow(d_prev_cw[d_prev_cw$program==0,]), prevalent=sum(d_prev_cw[d_prev_cw$program==0,]$prevalent))
  # 
  # svydes_cal1_cn <- survey::calibrate(svydes_wgtb1_cn, formula = ~prevalent,
  #                                  calfun = "raking", population = totals1_cn)
  #   
  # calibrated_prev_total_cn=svytotal(~prevalent_final,svydes_cal1_cn)    
  # 
  #   
#   
# calibrated_prev_total_cn[[1]]/nrow(d_prev_cw[d_prev_cw$program==0,])
# 
# ci2=calibrated_prev_total_cn[[1]]+c(-1,1)*1.96*10.081
# ci2/nrow(d_prev_cw[d_prev_cw$program==0,])
```







